# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI

on:
  push:
    branches: [ "master" ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: |
        make build
        make image
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        if [[ ${{ github.ref_name }} == "master" ]]; then make push-image; fi
        if [[ ${{ github.ref_name }} == "develop" ]]; then make push-develop; fi
        if [[ ${{ github.ref_type }} == "tag" ]]; then make push-tag; fi